package com.cmj.domain;

import java.math.BigDecimal;

public class Book {

	private Category category;
	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}


	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bid
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    private String bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bname
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    private String bname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.currPrice
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    private BigDecimal currprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.discount
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    private BigDecimal discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.press
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    private String press;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publishtime
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    private String publishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.total
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.wordNum
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    private Integer wordnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.cid
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.imagew
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    private String imagew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.imageb
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    private String imageb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.orderBy
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    private Integer orderby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bid
     *
     * @return the value of book.bid
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bid
     *
     * @param bid the value for book.bid
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bname
     *
     * @return the value of book.bname
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bname
     *
     * @param bname the value for book.bname
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public void setBname(String bname) {
        this.bname = bname == null ? null : bname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.currPrice
     *
     * @return the value of book.currPrice
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public BigDecimal getCurrprice() {
        return currprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.currPrice
     *
     * @param currprice the value for book.currPrice
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public void setCurrprice(BigDecimal currprice) {
        this.currprice = currprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.discount
     *
     * @return the value of book.discount
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.discount
     *
     * @param discount the value for book.discount
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.press
     *
     * @return the value of book.press
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.press
     *
     * @param press the value for book.press
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public void setPress(String press) {
        this.press = press == null ? null : press.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publishtime
     *
     * @return the value of book.publishtime
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public String getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publishtime
     *
     * @param publishtime the value for book.publishtime
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public void setPublishtime(String publishtime) {
        this.publishtime = publishtime == null ? null : publishtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.total
     *
     * @return the value of book.total
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.total
     *
     * @param total the value for book.total
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.wordNum
     *
     * @return the value of book.wordNum
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public Integer getWordnum() {
        return wordnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.wordNum
     *
     * @param wordnum the value for book.wordNum
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public void setWordnum(Integer wordnum) {
        this.wordnum = wordnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.cid
     *
     * @return the value of book.cid
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.cid
     *
     * @param cid the value for book.cid
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.imagew
     *
     * @return the value of book.imagew
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public String getImagew() {
        return imagew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.imagew
     *
     * @param imagew the value for book.imagew
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public void setImagew(String imagew) {
        this.imagew = imagew == null ? null : imagew.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.imageb
     *
     * @return the value of book.imageb
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public String getImageb() {
        return imageb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.imageb
     *
     * @param imageb the value for book.imageb
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public void setImageb(String imageb) {
        this.imageb = imageb == null ? null : imageb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.orderBy
     *
     * @return the value of book.orderBy
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public Integer getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.orderBy
     *
     * @param orderby the value for book.orderBy
     *
     * @mbg.generated Mon Jun 10 08:34:16 CST 2019
     */
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }
}