package com.cmj.domain;

import java.util.List;

public class Order {
	private User user;
	private List<OrderItem> orderItems;
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public List<OrderItem> getOrderItems() {
		return orderItems;
	}

	public void setOrderItems(List<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oid
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ordertime
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    private String ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    private double total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.address
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.uid
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    private String uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oid
     *
     * @return the value of order.oid
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.oid
     *
     * @param oid the value for order.oid
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ordertime
     *
     * @return the value of order.ordertime
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    public String getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ordertime
     *
     * @param date the value for order.ordertime
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    public void setOrdertime(String date) {
        this.ordertime = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total
     *
     * @return the value of order.total
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    public double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total
     *
     * @param d the value for order.total
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    public void setTotal(double d) {
        this.total = d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.address
     *
     * @return the value of order.address
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.address
     *
     * @param address the value for order.address
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.uid
     *
     * @return the value of order.uid
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.uid
     *
     * @param uid the value for order.uid
     *
     * @mbg.generated Mon Jun 17 13:35:54 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }
}