package com.cmj.domain;

import java.math.BigDecimal;

public class OrderItem {
	private Book book;//所关联的Book
	private Order order;//所属的订单
    public Book getBook() {
		return book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public Order getOrder() {
		return order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.orderItemId
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    private String orderitemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.quantity
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.subtotal
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    private double subtotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.bid
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    private String bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.bname
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    private String bname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.currPrice
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    private BigDecimal currprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.image_b
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    private String imageB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.oid
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    private String oid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.orderItemId
     *
     * @return the value of orderitem.orderItemId
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public String getOrderitemid() {
        return orderitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.orderItemId
     *
     * @param orderitemid the value for orderitem.orderItemId
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public void setOrderitemid(String orderitemid) {
        this.orderitemid = orderitemid == null ? null : orderitemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.quantity
     *
     * @return the value of orderitem.quantity
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.quantity
     *
     * @param quantity the value for orderitem.quantity
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.subtotal
     *
     * @return the value of orderitem.subtotal
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public double getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.subtotal
     *
     * @param d the value for orderitem.subtotal
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public void setSubtotal(double d) {
        this.subtotal = d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.bid
     *
     * @return the value of orderitem.bid
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.bid
     *
     * @param bid the value for orderitem.bid
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.bname
     *
     * @return the value of orderitem.bname
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.bname
     *
     * @param bname the value for orderitem.bname
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public void setBname(String bname) {
        this.bname = bname == null ? null : bname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.currPrice
     *
     * @return the value of orderitem.currPrice
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public BigDecimal getCurrprice() {
        return currprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.currPrice
     *
     * @param currprice the value for orderitem.currPrice
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public void setCurrprice(BigDecimal currprice) {
        this.currprice = currprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.image_b
     *
     * @return the value of orderitem.image_b
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public String getImageB() {
        return imageB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.image_b
     *
     * @param imageB the value for orderitem.image_b
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public void setImageB(String imageB) {
        this.imageB = imageB == null ? null : imageB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.oid
     *
     * @return the value of orderitem.oid
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.oid
     *
     * @param oid the value for orderitem.oid
     *
     * @mbg.generated Mon Jun 10 19:41:55 CST 2019
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }
}