package com.cmj.domain;

public class User {

	private String newpass;//新密码
	public String getNewpass() {
		return newpass;
	}

	public void setNewpass(String newpass) {
		this.newpass = newpass;
	}
	
	
	private String verifyCode;
	
    public String getVerifyCode() {
		return verifyCode;
	}

	public void setVerifyCode(String verifyCode) {
		this.verifyCode = verifyCode;
	}
	
	private String reloginpass;
	public String getReloginpass() {
		return reloginpass;
	}

	public void setReloginpass(String reloginpass) {
		this.reloginpass = reloginpass;
	}


	private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.loginname
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    private String loginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.loginpass
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    private String loginpass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.activationCode
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    private String activationcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.loginname
     *
     * @return the value of user.loginname
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.loginname
     *
     * @param loginname the value for user.loginname
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.loginpass
     *
     * @return the value of user.loginpass
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    public String getLoginpass() {
        return loginpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.loginpass
     *
     * @param loginpass the value for user.loginpass
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    public void setLoginpass(String loginpass) {
        this.loginpass = loginpass == null ? null : loginpass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.activationCode
     *
     * @return the value of user.activationCode
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    public String getActivationcode() {
        return activationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.activationCode
     *
     * @param activationcode the value for user.activationCode
     *
     * @mbg.generated Wed Jun 05 20:04:55 CST 2019
     */
    public void setActivationcode(String activationcode) {
        this.activationcode = activationcode == null ? null : activationcode.trim();
    }
}