package com.cmj.dao;

import com.cmj.domain.Cartitem;
import com.cmj.domain.CartitemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CartitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Mon Jun 10 07:59:08 CST 2019
     */
    long countByExample(CartitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Mon Jun 10 07:59:08 CST 2019
     */
    int deleteByExample(CartitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Mon Jun 10 07:59:08 CST 2019
     */
    int deleteByPrimaryKey(String cartitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Mon Jun 10 07:59:08 CST 2019
     */
    int insert(Cartitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Mon Jun 10 07:59:08 CST 2019
     */
    int insertSelective(Cartitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Mon Jun 10 07:59:08 CST 2019
     */
    List<Cartitem> selectByExample(CartitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Mon Jun 10 07:59:08 CST 2019
     */
    Cartitem selectByPrimaryKey(String cartitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Mon Jun 10 07:59:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Cartitem record, @Param("example") CartitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Mon Jun 10 07:59:08 CST 2019
     */
    int updateByExample(@Param("record") Cartitem record, @Param("example") CartitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Mon Jun 10 07:59:08 CST 2019
     */
    int updateByPrimaryKeySelective(Cartitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Mon Jun 10 07:59:08 CST 2019
     */
    int updateByPrimaryKey(Cartitem record);

    Cartitem findtotal(String cartstring);

	List<Cartitem> myCart(String uid);

	Cartitem findByUidBid(Cartitem cartitem);

	void updateQuantity(int quantity,String cartitemid);

	Cartitem findByCartItemId(String cartitemid);

	void batchDelete(String[] cartitemid);

	List<Cartitem> settleCart(String[] cartitemid);
}